server:
  port: 44000
spring:
  application:
    name: test-rabbitmq-producer
  rabbitmq:
    host: 47.100.77.11
    port: 5672
    username: han
    password: Han#222
    virtualHost: /
  redis:
    host: 127.0.0.1
    port: 6379
    password: